name: "Home Assistant PTT"
version: "1.0.0"
slug: "ha_phone_ptt"
description: "Push-to-Talk Add-on for Home Assistant"
url: "https://github.com/letomix/ha-phone-ptt"
startup: application
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:microphone
ports:
  8099/tcp: 8099
schema: {}
